#pragma once
#include <cstdint>

// NotesIcon: 32x32, 1-bit MSB-first (bit 1 = white/background, 0 = ink) — outline pencil for the
// "Notes" menu item. Thin 2px strokes to match the other CrossPoint menu icons (lock.h, fetch.h).
//
// Authored PRE-ROTATED 90 deg CCW (stored[r][c] = upright[c][31-r]) so it displays upright after
// the panel's 90 deg CW blit rotation — same convention as lock.h / fetch.h / PaperbitIcon.
//
// On-screen appearance (un-rotated preview of the byte array below; '#' = ink):
//   ................................
//   ................................
//   ................................
//   ................................
//   ................................
//   ....................##..........
//   ...................####.........
//   ..................##..##........
//   .................###...##.......
//   ................##.##...##......
//   ...............##...##...##.....
//   ..............##.....##.##......
//   .............##.......###.......
//   ............##........##........
//   ...........##........##.........
//   ..........##........##..........
//   .........##........##...........
//   ........##........##............
//   .......##........##.............
//   ......##........##..............
//   ......##.......##...............
//   .....####.....##................
//   .....#####...##.................
//   .....######.##..................
//   .....########...................
//   ....######......................
//   ....##..........................
//   ................................
//   ................................
//   ................................
//   ................................
//   ................................
static const uint8_t NotesIcon[] = {
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xDF, 0xFF, 0xFF, 0xFF, 0x8F, 0xFF, 0xFF, 0xFF, 0x27, 0xFF, 0xFF,
    0xFE, 0x73, 0xFF, 0xFF, 0xFC, 0xE1, 0xFF, 0xFF, 0xF9, 0xCC, 0xFF, 0xFF, 0xF9, 0x9E, 0x7F, 0xFF,
    0xFC, 0x3F, 0x3F, 0xFF, 0xFE, 0x7F, 0x9F, 0xFF, 0xFF, 0x3F, 0xCF, 0xFF, 0xFF, 0x9F, 0xE7, 0xFF,
    0xFF, 0xCF, 0xF3, 0xFF, 0xFF, 0xE7, 0xF9, 0xFF, 0xFF, 0xF3, 0xFC, 0xFF, 0xFF, 0xF9, 0xFE, 0x7F,
    0xFF, 0xFC, 0xFF, 0x7F, 0xFF, 0xFE, 0x7E, 0x7F, 0xFF, 0xFF, 0x3C, 0x3F, 0xFF, 0xFF, 0x98, 0x3F,
    0xFF, 0xFF, 0xC0, 0x3F, 0xFF, 0xFF, 0xE0, 0x3F, 0xFF, 0xFF, 0xF8, 0x1F, 0xFF, 0xFF, 0xFF, 0x9F,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};
